
app:
  dummy:
    enabled: true
    totalUsers: 30
    minBooksPerUser: 7
    maxBooksPerUser: 40
    booksStartYear: 1930
    

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    com.ex.books: DEBUG





